name: Debug
on:
  push:
    branches: [ "install_all_dependencies" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  OPENMS_VERSION: 3.2.0 
  # Define needed TOPP tools here
  TOPP_TOOLS: "FeatureFinderMetabo MetaboliteAdductDecharger SiriusExport"

jobs:
  build-executable:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: 3.11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python embeddable version
      run: |
        mkdir python-${{ env.PYTHON_VERSION }}
        curl -O https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/python-${{ env.PYTHON_VERSION }}-embed-amd64.zip
        unzip python-${{ env.PYTHON_VERSION }}-embed-amd64.zip -d python-${{ env.PYTHON_VERSION }}
        rm python-${{ env.PYTHON_VERSION }}-embed-amd64.zip

    - name: Install pip
      run: |
        curl -O https://bootstrap.pypa.io/get-pip.py
        ./python-${{ env.PYTHON_VERSION }}/python get-pip.py --no-warn-script-location
        rm get-pip.py

    - name: Uncomment 'import site' in python311._pth file
      run: |
        sed -i 's/#import site/import site/' python-${{ env.PYTHON_VERSION }}/python311._pth

    - name: Install Required Packages
      run: .\python-${{ env.PYTHON_VERSION }}\python -m pip install --force-reinstall -r requirements.txt --no-warn-script-location

    - name: Create run_app.bat file
      run: |
        echo '@echo off' > run_app.bat
        echo '.\\python-${{ env.PYTHON_VERSION }}\\python -m streamlit run app.py local' >> run_app.bat
  
    - name: List Root Folder
      run: |
        dir

    - name: Move All Files to Folder
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path artifact_folder
        Get-ChildItem -Path . -Exclude artifact_folder | ForEach-Object {
            Move-Item -Path $_.FullName -Destination artifact_folder
        }


    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: artifact_folder